Repository Deep-Caffeine/Server, pull requests merged in 2023-05, with the labels that each got.

#7 User 관련 Controller 생성(#2)
  server/ApplicationDbContext.cs
  server/Controllers/UserController.cs
  server/Entity/BaseEntity.cs
  server/Entity/UserEntity.cs
  server/server.csproj
  server/server.sln
Labels: enhancement

#13 Dockerfile 및 docker-compose 파일 작성 (#3)
  .env
  .gitignore
  database/Dockerfile
  database/my.cnf
  docker-compose.yml
  server/.dockerignore
  server/Dockerfile
Labels: enhancement

#9 User Controller Request 버그 수정 (#8)
  server/ApplicationDbContext.cs
  server/Controllers/UserController.cs
  server/Program.cs
Labels: bug

#10 User 관련 더미 데이터 반환 (#5)
  .gitignore
  server/ApplicationDbContext.cs
  server/Controllers/UserController.cs
  server/DTOs/ErrorResponse.cs
  server/DTOs/GetUserResponse.cs
  server/DTOs/KeyValueErrorResponse.cs
  server/Entity/BaseEntity.cs
  server/Entity/UserEntity.cs
  server/Program.cs
Labels: enhancement

#12 UserService 생성 및 의존성 주입 (#6)
  .gitignore
  server/Controllers/UserController.cs
  server/Interface/IUserService.cs
  server/Program.cs
  server/Services/UserService.cs
Labels: enhancement

#17 Entity 디렉토리에 대한 명칭 변경 (#16)
  server/ApplicationDbContext.cs
  server/Controllers/UserController.cs
  server/Entities/BaseEntity.cs
  server/Entities/UserEntity.cs
  server/server.csproj
Labels: wontfix

#24 User Entity Attribute 추가(#22)
  server/Controllers/UserController.cs
  server/Entities/UserEntity.cs
Labels: enhancement

#26 개발 단계 CORS 정책 허용 (#23)
  server/Program.cs
Labels: bug

#29 개발단계에서 Swagger 문서를 확인할 수 없는 문제(#25)
  server/Program.cs
Labels: invalid

#32 Github Actions 구성 (#4)
  .github/workflows/dotnet-ef-migration.yml
  .github/workflows/pull-request.yml
  server/Controllers/UserController.cs
  server/Entities/UserEntity.cs
  server/Program.cs
  server/Services/UserService.cs
Labels: enhancement
