Repository Deep-Caffeine/Server, pull requests merged in 2023-08, with the labels that each got.

#45 Chat 관련 Entity 추가 (#43)
  server/Entities/ChatLogsEntity.cs
  server/Entities/ChatParticipantsEntity.cs
  server/Entities/ChatRoomEntity.cs
  server/server.csproj
Labels: enhancement

#47 UserEntity 수정 및 ChatParticipantsEntity 미상속 부분 해결 (#41)
  server/DTOs/GetUserResponse.cs
  server/DTOs/PutUserRequest.cs
  server/Entities/ChatParticipantsEntity.cs
  server/Entities/UserEntity.cs
Labels: bug

#53 내부 변수 표기 방법, 디렉토리 구조 고도화, gitIgnore 변경 등 프로젝트 Style 수정
  .gitignore
  server/DTOs/Auth/AuthRequest.cs
  server/DTOs/Auth/AuthResponse.cs
  server/DTOs/Auth/GetUserResponse.cs
  server/DTOs/Auth/KeyValueErrorResponse.cs
  server/DTOs/Auth/PutUserRequest.cs
  server/Data/Migrations/20230601190207_ (31ec2fe).Designer.cs
  server/Data/Migrations/20230601190207_ (31ec2fe).cs
  server/Data/Migrations/ApplicationDbContextModelSnapshot.cs
  server/Services/AuthService.cs
  server/Services/ChatHttpService.cs
  server/Services/UserService.cs
  server/server.csproj
Labels: wontfix
